### ISSUE TITLE
Question: Will the sample Apps  work on  a  x86/x86_64 virtual device on Andriod Studio 

### ISSUE THREAD

**Issue by RyanFordio** [google/filament#1413]
I could debug/run the sample apps using real phone. but  could no trun /debug using  a virtual device on Android Studio. It always failed  to create the Engine no mater what I use x86 /x86_64

Anyone has experience to run the apps on virtual device, could you please share your steps?
Thanks
Ryan

**Comment by romainguy** [comment]
They work in AVDs yes. What failure do you get in logcat?

**Comment by RyanFordio** [comment]
error information from logcat:

/Filament: eglChooseConfig failed with unknown
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.textured, PID: 16214
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.filament.textured/com.google.android.filament.textured.MainActivity}: java.lang.IllegalStateException: Couldn't create Engine
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.IllegalStateException: Couldn't create Engine
        at com.google.android.filament.Engine.create(Engine.java:46)
        at com.google.android.filament.textured.MainActivity.setupFilament(MainActivity.kt:111)
        at com.google.android.filament.textured.MainActivity.onCreate(MainActivity.kt:95)
        at android.app.Activity.performCreate(Activity.java:7783)
        at android.app.Activity.performCreate(Activity.java:7772)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3235)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7319) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

**Comment by RyanFordio** [comment]
E/Filament: eglChooseConfig failed with error code: 12288

**Comment by RyanFordio** [comment]
from  Khronos Group's egl.h, 12888 = 0x3000 is suceess
#define EGL_SUCCESS                       0x3000

**Comment by romainguy** [comment]
How is your AVD setup?

**Comment by RyanFordio** [comment]
![avd](https://user-images.githubusercontent.com/52858405/61495789-02416f80-a988-11e9-962c-a9f748ce31bd.png)

**Comment by romainguy** [comment]
Thanks. Can you try by setting GPU emulation to hardware? And software if that doesn't work.

**Comment by RyanFordio** [comment]
I had tried using hardware and software. I got same error

D/: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr **ANDROID_EMU_gles_max_version_2** 
E/Filament: eglChooseConfig 1 failed with error code: 0x3000
    eglChooseConfig failed with unknown

**Comment by romainguy** [comment]
Your max GLES must be 3, not 2. Filament cannot run on ES 2.0.

**Comment by RyanFordio** [comment]
do you know what's configuration could let the emulator use GLES 3.0?  I only could select GLES 2.0 
Thanks

**Comment by romainguy** [comment]
You shouldn't have to do anything special but I've had issues in the past with x86_64 AVDs. Either try with x86 or with a different type of system image (with/without Google APIs, etc.). I unfortunately can't remember which variant caused me issues.

**Comment by RyanFordio** [comment]
Thanks, fixed,

need put 
GLESDynamicVersion = on  in the file ~/.android/advancedFeatures.ini

**Comment by griffin2000** [comment]
@RyanFordio anything you need to do after creating ~/.android/advancedFeatures.ini and setting that flag?  I've don't that restarted Android Studio, but still only get GLES20 options for the AVD:
![image](https://user-images.githubusercontent.com/1008962/62642460-c14bd380-b913-11e9-94a8-5b49b5381591.png)
