### ISSUE TITLE
gltfio load gltf error

### ISSUE THREAD

**Issue by jaccen** [google/filament#1436]
1、in java，i use this for load gltf：

      MaterialProvider mp = new MaterialProvider(engine);
        assetLoader = new AssetLoader(engine, mp, EntityManager.get());
        try {
            InputStream stream = getAssets().open("models/lucy.glb");
            byte[] bytes = new byte[stream.available()];
            stream.read(bytes);
            assetLoader.createAssetFromBinary(ByteBuffer.wrap(bytes));
        } catch (IOException e) {
            e.printStackTrace();
        }
        scene.addEntities(filamentAsset.getEntities());

2、error：

19967-19967/com.example.myfilament E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myfilament, PID: 19967
    java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.filament.gltfio.MaterialProvider.nCreateMaterialProvider(long) (tried Java_com_google_android_filament_gltfio_MaterialProvider_nCreateMaterialProvider and Java_com_google_android_filament_gltfio_MaterialProvider_nCreateMaterialProvider__J)
        at com.google.android.filament.gltfio.MaterialProvider.nCreateMaterialProvider(Native Method)
        at com.google.android.filament.gltfio.MaterialProvider.<init>(MaterialProvider.java:40)
        at com.example.myfilament.MainActivity.setupScene(MainActivity.java:155)
        at com.example.myfilament.MainActivity.onCreate(MainActivity.java:93)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

how can i resolve this？

**Comment by romainguy** [comment]
The JNI library cannot be found. You need to call AssetLoader.init() first.
