### ISSUE TITLE
BindingError occurs when loading textures on some glTF models

### ISSUE THREAD

**Issue by cx20** [google/filament#1565]
**Describe the bug**
I tried to display [Sponza.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza) with filament v1.3.2.
However, the model fails to display with a `BindingError` when loading the texture.

```
filament.js:6 
Uncaught 
BindingError
message: "Cannot pass "[object HTMLImageElement]" as a driver$BufferDescriptor"
name: "BindingError"
stack: 
"BindingError: Cannot pass "[object HTMLImageElement]" as a driver$BufferDescriptor
    at BindingError.<anonymous> (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:92309)
    at new BindingError (eval at createNamedFunction (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:92018), <anonymous>:4:34)
    at throwBindingError (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:97436)
    at RegisteredPointer.nonConstNoSmartPtrRawPointerToWireType [as toWireType] (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:105535)
    at gltfio$ResourceLoader$addResourceData [as addResourceData] (eval at new_ (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:115064), <anonymous>:9:26)
    at https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:266067
    at Image.img.onload (https://cx20.github.io/gltf-test/libs/filament/v1.3.2/filament.js:6:260434)"
__proto__: Error
constructor: ƒ BindingError()
toString: ƒ ()
__proto__: Object
```

**To Reproduce**
[filament v1.3.2 + Sponza.gltf result](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=Sponza&scale=1&type=glTF)
[filament v1.3.2 + AlphaBlendModeTest.gltf result](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
[filament v1.3.2 + MorphPrimitivesTest.gltf result](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=MorphPrimitivesTest&scale=2&type=glTF)

**Expected behavior**
It is expected to be displayed similar to the sample below.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza

**Screenshots**
There is no reference screen because the model is not displayed.

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1903 (OS Build 18362.295)
- GPU: Intel HD Graphics 520
- Backend: ANGLE
- Browser: Chrome 76

**Comment by cx20** [comment]
I confirmed that this problem has been fixed in the latest version of filament.
[filament latest version + Sponza.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=Sponza&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/63893302-c983c400-ca24-11e9-9724-ac30cfc174ed.png)

**Comment by dmitrykolesnikovich** [comment]
> I tried to display [Sponza.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Sponza) with filament v1.3.2.

Could you please share how exactly you view Sponza.gltf with Filament and if with [gltf_viewer sample](https://github.com/google/filament/blob/main/samples/gltf_viewer.cpp) then how do you fly with camera? (WASD do not work).

**Comment by dmitrykolesnikovich** [comment]
The only way I can browse GLTF now is by useing my mouse wheel https://www.youtube.com/watch?v=AuN6T_C5HPE
