### ISSUE TITLE
Hello Triangle sample crash on some device but working on others.

### ISSUE THREAD

**Issue by R4md4c** [google/filament#2019]
**Describe the bug**
When trying to run from Android Studio on a relatively old device [Sony Xperia Z3](https://www.gsmarena.com/sony_xperia_z3-6539.php) (runs Android 6.0 and supports OpenGL ES 3.0), the sample crash with the following stacktrace. 

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memmove8" referenced by "/data/app/com.google.android.filament.ibl-1/lib/arm/libfilament-jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.google.android.filament.Filament.<clinit>(Filament.java:22)
        at com.google.android.filament.Filament.init(Filament.java:30)
        at com.google.android.filament.ibl.MainActivity.<clinit>(MainActivity.kt:41)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
```

**To Reproduce**
1. `./build.sh -p desktop -i release`
2. `./build.sh -p android release`
3. `./gradlew :samples:sample-hello-triangle:installDebug`

**Expected behavior**
Application runs normally

**Smartphone (please complete the following information):**
 - Device: Sony Xperia Z3 
 - OS: Android 6.0

**Additional context**
The same sample runs on a newer device (Samsung S10e), and AVD (after forcing it to use OpenGL ES 3.0).

Note: Using the latest master.

**Comment by romainguy** [comment]
We recently made a fix for this. Let us know if it still happens.
