### ISSUE TITLE
Filament.init() in android giving same jobid in systemuid error

### ISSUE THREAD

**Issue by nakshathru** [google/filament#2518]
I was trying to run filament along with mediapipe for rendering 3d models on top of camera stream. 
(It's a bazel project with java )
I'm using maven dependency for filament 
(`com.google.android.filament:filament-android:1.6.0`)

Since it is the first step , can't see any other mistake
Tried running by removing all mediapipe initialization, but the error still exist
Any idea why this is happening ??

Attaching the error from logcat

`2020-05-12 02:37:22.696 1361-3668/? E/JobScheduler: jobid:20536
    java.lang.IllegalStateException: Same jobid in systemuid.
        at com.android.server.job.JobSchedulerService.scheduleAsPackage(JobSchedulerService.java:888)
        at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2592)
        at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
        at com.android.server.backup.FullBackupJob.schedule(FullBackupJob.java:54)
        at com.android.server.backup.BackupManagerService$3.run(BackupManagerService.java:1925)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by romainguy** [comment]
This has nothing to do with Filament. It's a system Job scheduled by the backup service. It's not related to MediaPipe either I believe. I have no idea what would cause this but it's finitely not our library.

**Comment by nakshathru** [comment]
Thanks for enlightening me.
I switched entire project to gradle from bazel 
Now it's working fine though .
