### ISSUE TITLE
UnsatisfiedLinkError filament-jni.dll can't find dependent libraries

### ISSUE THREAD

**Issue by MovementSpeed** [google/filament#2583]
Hello,
I'm trying to use Filament on Windows on Java\Kotlin with JNI bindings.

I added filament-java.jar into the /libs folder on my gradle application module (I'm using IntelliJ) and added it to the gradle dependencies.

Then, I created this class:
```kotlin
import com.google.android.filament.Filament
import java.awt.EventQueue
import javax.swing.JFrame

class Windows : JFrame() {

    init {
        Filament.init()
        createUI(title)
    }

    private fun createUI(title: String) {
        setTitle(title)

        defaultCloseOperation = EXIT_ON_CLOSE
        setSize(1280, 720)
        setLocationRelativeTo(null)
    }
}

private fun createAndShowGUI() {
    val frame = Windows()
    frame.isVisible = true
}

fun main() {
    EventQueue.invokeLater(::createAndShowGUI)
}
```

When running the main function, it crashes with the error on the title:
`
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Windows\System32\filament-jni.dll: Can't find dependent libraries
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1850)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.google.android.filament.Filament.<clinit>(Filament.java:22)
	at com.movementspeed.blackfilament.windows.Windows.<init>(Windows.kt:11)
	at com.movementspeed.blackfilament.windows.WindowsKt.createAndShowGUI(Windows.kt:26)
	at com.movementspeed.blackfilament.windows.WindowsKt.access$createAndShowGUI(Windows.kt:1)
	at com.movementspeed.blackfilament.windows.WindowsKt$main$1.invoke(Windows.kt:31)
	at com.movementspeed.blackfilament.windows.WindowsKt$main$1.invoke(Windows.kt)
	at com.movementspeed.blackfilament.windows.WindowsKt$sam$java_lang_Runnable$0.run(Windows.kt)
`

As you can see, I've put filament-jni.dll on my system32 folder.
I don't really know what are the dependent libraries it's talking about, can you help me figure it out?

Thanks.

**Comment by romainguy** [comment]
You should use something like https://github.com/lucasg/Dependencies to figure out what the dependencies of the DLL are. It's probably the msvc runtime that needs to be installed.

**Comment by MovementSpeed** [comment]
> You should use something like https://github.com/lucasg/Dependencies to figure out what the dependencies of the DLL are. It's probably the msvc runtime that needs to be installed.

Solved, thank you.

There was in fact a missing dependency because I didn't set the PATH to the JRE bin directory, containing jawt.dll.

**Comment by romainguy** [comment]
thanks!
