### ISSUE TITLE
About studio_ small_ 02_ 2K

### ISSUE THREAD

**Issue by qmz13579** [google/filament#2764]
W/System.err: java.io.FileNotFoundException: studio_small_02_2k/m5_px.rgb32f
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:942)
        at android.content.res.AssetManager.open(AssetManager.java:919)
W/System.err:     at com.example.filamentdemo.IblLoader.loadCubemap(sample_page_curl.java:651)
        at com.example.filamentdemo.IblLoader.loadIndirectLight(sample_page_curl.java:622)
        at com.example.filamentdemo.sample_page_curl.onCreate(sample_page_curl.java:171)
        at android.app.Activity.performCreate(Activity.java:8085)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4074)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2473)
        at android.os.Handler.dispatchMessage(Handler.java:110)
W/System.err:     at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/Filament: in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "ROUGHNESS" not found
    in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "APEX" not found
    in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "THETA" not found
    in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "USE_CPU" not found
E/Filament: in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "USE_CPU" not found
E/Filament: in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "APEX" not found
    in ssize_t filament::UniformInterfaceBlock::getUniformOffset(const char *, size_t) const:120
    reason: uniform named "THETA" not found
E/Filament: in const SamplerInterfaceBlock::SamplerInfo *filament::SamplerInterfaceBlock::getSamplerInfo(const char *) const:110
    reason: sampler named "IMAGE_A" not found
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 32239 (le.filamentdemo), pid 32239 (le.filamentdemo)

  The output file of rgb32:   cmgen.exe f rgb32f -x small studio 2k.hdr

  Missing file after build

  **Which question, please**

**Comment by romainguy** [comment]
It looks like neither the IBL nor the materials were compiled. Make sure you've built and installed the filament host tools in the proper directory. Check the readmes/building files for more info.
