### ISSUE TITLE
App crashing on calling of  engine.destroy() inside fragment

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#3039]
I am using Fragment to load Model with ModelViewer
and I am creating an engine on onCreate of fragment like the below code.everything is working fine.
but when I try to destroy the engine on OnDestroy of fragment it throws below error.

   ```
 java.lang.RuntimeException: Unable to destroy activity activities.MainActivity}: java.lang.IllegalStateException: Calling method on destroyed Engine
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5176)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5205)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7604)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: java.lang.IllegalStateException: Calling method on destroyed Engine
        at com.google.android.filament.Engine.getNativeObject(Engine.java:652)
        at com.google.android.filament.Engine.destroy(Engine.java:244)
        at 
`CustomizedProductFragment.onDestroy(CustomizedProductFragment.kt:107)`
        at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2927)
        at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:492)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1296)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2609)
        at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
        at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
        at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:242)
        at android.app.Activity.performDestroy(Activity.java:8068)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1363)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5205) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:241) 
        at android.app.ActivityThread.main(ActivityThread.java:7604) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941) 
```

Here is my code.

```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setupFilament()
    }


 override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        setTitle()
      
        initFilament()
      
    }


  private fun setupFilament(){
        choreographer = Choreographer.getInstance()
        engine = Engine.create()
    }

    /**
     * Initialize filament and Start loading Model
     */
    private fun initFilament() {

        manipulator = Manipulator.Builder()
            .targetPosition(0.0f, 0.0f, -4.0f)
            .orbitHomePosition(0f, 0.0f, -1.25f)
            .viewport(mySurfaceView.width, mySurfaceView.height)
            .build(Manipulator.Mode.ORBIT)

        modelViewer = ModelViewer(mySurfaceView, engine, manipulator)

        createRenderables()
        createIndirectLight()

        mySurfaceView.setOnTouchListener { _, event ->
            modelViewer.onTouchEvent(event)
            true
        }

        //once everything is loaded setup default configuration for model
        FilamentCustomizationUtils.setupDefaultConfiguration(modelViewer)
    }

    private fun createIndirectLight() {
        val scene = modelViewer.scene
        val ibl = "venetian_crossroads_2k"

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx")
            scene.indirectLight = KtxLoader.createIndirectLight(engine, byteBuffer)
            scene.indirectLight!!.intensity = 30_000.0f
        }

        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx")
            scene.skybox = KtxLoader.createSkybox(engine, byteBuffer)
        }
        scene.skybox = Skybox.Builder().color(01f, 01f, 01f, 01f).build(engine)
    }

    private fun createRenderables() {
        viewLifecycleOwner.lifecycleScope.launch {
            val byteBuffer = readCompressedAsset("models/CUSTOMFX_FX870_ANDROID_ASSET.gltf")
            modelViewer.loadModelGltfAsync(byteBuffer) { uri -> readCompressedAsset("models/$uri") }
            modelViewer.transformToUnitCube()
        }
    }

    private fun readCompressedAsset(assetName: String): ByteBuffer {
        val input = activity?.assets?.open(assetName)
        val bytes = ByteArray(input?.available()!!)
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }

    override fun onResume() {
        super.onResume()
        choreographer.postFrameCallback(frameScheduler)
    }

    override fun onPause() {
        super.onPause()
        choreographer.removeFrameCallback(frameScheduler)
    }


 override fun onDestroy() {
        super.onDestroy()
        choreographer.removeFrameCallback(frameScheduler)
        modelViewer.destroyModel()
        //crashes here.
        engine.destroy()
    }

    inner class FrameCallback : Choreographer.FrameCallback {
        private val startTime = System.nanoTime()
        override fun doFrame(frameTimeNanos: Long) {
            choreographer.postFrameCallback(this)
            modelViewer.animator?.apply {
                if (animationCount > 0) {
                    val elapsedTimeSeconds =
                        (frameTimeNanos - startTime).toDouble() / 1_000_000_00000000000
                    applyAnimation(0, elapsedTimeSeconds.toFloat())
                }
                updateBoneMatrices()
            }

            modelViewer.render(frameTimeNanos)
        }
    }
```

**Comment by romainguy** [comment]
The reason is here:

```
  Caused by: java.lang.IllegalStateException: Calling method on destroyed Engine
     at com.google.android.filament.Engine.getNativeObject(Engine.java:652)
     at com.google.android.filament.Engine.destroy(Engine.java:244)
```

The engine is being destroyed twice because `ModelView` will take care of the destruction for you. Simply don't call `destroy()` manually.
