### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by Zumbalamambo** [google/filament#3380]
I'm using the following code to load the 3d model,

```
class MainActivity : Activity() {

    companion object {
        // Load the library for the utility layer, which in turn loads gltfio and the Filament core.
        init { Utils.init() }
    }

    private lateinit var surfaceView: SurfaceView
    private lateinit var choreographer: Choreographer
    private val frameScheduler = FrameCallback()
    private lateinit var modelViewer: ModelViewer
    private val doubleTapListener = DoubleTapListener()
    private lateinit var doubleTapDetector: GestureDetector

    @SuppressLint("ClickableViewAccessibility")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        surfaceView = SurfaceView(this).apply { setContentView(this) }
        choreographer = Choreographer.getInstance()

        doubleTapDetector = GestureDetector(applicationContext, doubleTapListener)

        modelViewer = ModelViewer(surfaceView)

        surfaceView.setOnTouchListener { _, event ->
            modelViewer.onTouchEvent(event)
            doubleTapDetector.onTouchEvent(event)
            true
        }

        createRenderables()
        createIndirectLight()

        val dynamicResolutionOptions = modelViewer.view.dynamicResolutionOptions
        dynamicResolutionOptions.enabled = true
        modelViewer.view.dynamicResolutionOptions = dynamicResolutionOptions

        val ssaoOptions = modelViewer.view.ambientOcclusionOptions
         // ssaoOptions.enabled = true
        modelViewer.view.ambientOcclusionOptions = ssaoOptions

        val bloomOptions = modelViewer.view.bloomOptions
        bloomOptions.enabled = true
        modelViewer.view.bloomOptions = bloomOptions
    }

    private fun createRenderables() {
        val buffer = assets.open("models/home.glb").use { input ->
            val bytes = ByteArray(input.available())
            input.read(bytes)
            ByteBuffer.wrap(bytes)
        }

        modelViewer.loadModelGltfAsync(buffer) { uri -> readCompressedAsset("models/$uri") }
        modelViewer.transformToUnitCube()
    }

    private fun createIndirectLight() {
        val engine = modelViewer.engine
        val scene = modelViewer.scene
        val ibl = "venetian_crossroads_2k"
        readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx").let {
            scene.indirectLight = KtxLoader.createIndirectLight(engine, it)
            scene.indirectLight!!.intensity = 30_000.0f
        }
        readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
            scene.skybox = KtxLoader.createSkybox(engine, it)
        }
    }

    private fun readCompressedAsset(assetName: String): ByteBuffer {
        val input = assets.open(assetName)
        val bytes = ByteArray(input.available())
        input.read(bytes)
        return ByteBuffer.wrap(bytes)
    }

    override fun onResume() {
        super.onResume()
        choreographer.postFrameCallback(frameScheduler)
    }

    override fun onPause() {
        super.onPause()
        choreographer.removeFrameCallback(frameScheduler)
    }

    override fun onDestroy() {
        super.onDestroy()
        choreographer.removeFrameCallback(frameScheduler)
    }

    inner class FrameCallback : Choreographer.FrameCallback {
        private val startTime = System.nanoTime()
        override fun doFrame(frameTimeNanos: Long) {
            choreographer.postFrameCallback(this)

            modelViewer.animator?.apply {
                if (animationCount > 0) {
                    val elapsedTimeSeconds = (frameTimeNanos - startTime).toDouble() / 1_000_000_000
                    applyAnimation(0, elapsedTimeSeconds.toFloat())
                }
                updateBoneMatrices()
            }

            modelViewer.render(frameTimeNanos)
        }
    }

    inner class DoubleTapListener : GestureDetector.SimpleOnGestureListener() {
        override fun onDoubleTap(e: MotionEvent?): Boolean {
            modelViewer.destroyModel()
            createRenderables()
            return super.onDoubleTap(e)
        }
    }
}

```

But it throws the following error,

```
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   - locked <0x01630fab> (a android.content.res.AssetManager)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at android.content.res.AssetManager.open(AssetManager.java:833)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.com.modelviewer.MainActivity.readCompressedAsset(MainActivity.kt:87)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.com.modelviewer.MainActivity.access$readCompressedAsset(MainActivity.kt:16)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.com.modelviewer.MainActivity$createRenderables$1.invoke(MainActivity.kt:69)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.com.modelviewer.MainActivity$createRenderables$1.invoke(MainActivity.kt:16)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.google.android.filament.utils.ModelViewer.fetchResources(ModelViewer.kt:308)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at com.google.android.filament.utils.ModelViewer$loadModelGltfAsync$1.invokeSuspend(ModelViewer.kt:194)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630]   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/.com.modelviewe: runtime.cc:630] 
    
    --------- beginning of crash
2020-12-20 15:05:31.408 6872-6965/com.com.modelviewer A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6965 (DefaultDispatch), pid 6872 (.com.modelviewer)

```

How can I fix it?

**Comment by romainguy** [comment]
The files you are trying to load cannot be found. Make sure you have them properly installed in the right directories.
