### ISSUE TITLE
Manipulator FLIGHT_MODE can't be setup on Android

### ISSUE THREAD

**Issue by wpinaud** [google/filament#3538]
**Describe the bug**
Hi ! While trying to build a dolly cam behaviour using the Camera Manipulator I've noticed an issue on Android:
When trying to set `.flightStartPosition` or `flightStartOrientation` or `flightMaxMoveSpeed` or `flightSpeedSteps` or `flightPanSpeed` the application is crashing as the native implementation of these method can't be found.

**To Reproduce**
1. Setup a manipulator with `.flightStartPosition` or `flightStartOrientation` or `flightMaxMoveSpeed` or `flightSpeedSteps` or `flightPanSpeed`
2. Attach this manipulator to a ModelViewer
3. Build and run on an Android device
4. Application is crashing

Example code:
```
val manipulator = Manipulator
            .Builder()
            .flightStartPosition(10f, 10f, 10f)
            .flightStartOrientation(40f, 40f)
            .flightMaxMoveSpeed(12f)
            .flightSpeedSteps(4)
            .flightPanSpeed(23f, 23f)
            .viewport(surfaceView.width, surfaceView.height)
            .build(Manipulator.Mode.FREE_FLIGHT)

val modelViewer = ModelViewer(surfaceView, manipulator = manipulator)
```

**Expected behavior**
The method calls should be implemented :) 

**Stacktrace**
 ```
2021-02-16 17:57:05.851 29581-29581/com.filament_gltf_loader E/ent_gltf_loade: No implementation found for void com.google.android.filament.utils.Manipulator.nFlightStartPosition(long, float, float, float) (tried Java_com_google_android_filament_utils_Manipulator_nFlightStartPosition and Java_com_google_android_filament_utils_Manipulator_nFlightStartPosition__JFFF)
2021-02-16 17:57:05.853 29581-29581/com.filament_gltf_loader E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.filament_gltf_loader, PID: 29581
    java.lang.UnsatisfiedLinkError: No implementation found for void com.google.android.filament.utils.Manipulator.nFlightStartPosition(long, float, float, float) (tried Java_com_google_android_filament_utils_Manipulator_nFlightStartPosition and Java_com_google_android_filament_utils_Manipulator_nFlightStartPosition__JFFF)
        at com.google.android.filament.utils.Manipulator.nFlightStartPosition(Native Method)
        at com.google.android.filament.utils.Manipulator.access$1200(Manipulator.java:34)
        at com.google.android.filament.utils.Manipulator$Builder.flightStartPosition(Manipulator.java:202)
```

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11

**Comment by romainguy** [comment]
The methods are implemented but not named correct. I'll fix it right now, thank you!

**Comment by wpinaud** [comment]
Thank YOU for this amazing rendering engine!
