### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by wudelu** [google/filament#3579]
1.sample-hello-camera
          logcat:
            Process: com.google.android.filament.hellocamera, PID: 17366
              java.lang.NoSuchMethodError: No virtual method getHardwareBuffer()Landroid/hardware/HardwareBuffer; in class Landroid/media/Image; or its super classes (declaration of 'android.media.Image' appears in /system/framework/framework.jar)
                  at com.google.android.filament.hellocam.CameraHelper.pushExternalImageToFilament(CameraHelper.kt:90)
                  at com.google.android.filament.hellocam.MainActivity$FrameCallback.doFrame(MainActivity.kt:366)
                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
                  at android.view.Choreographer.doCallbacks(Choreographer.java:790)
                  at android.view.Choreographer.doFrame(Choreographer.java:718)
                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
                  at android.os.Handler.handleCallback(Handler.java:808)
                  at android.os.Handler.dispatchMessage(Handler.java:101)
                  at android.os.Looper.loop(Looper.java:166)
                  at android.app.ActivityThread.main(ActivityThread.java:7425)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
                  
        
 2.device 
     HUAWEI Mate9
     android 8.0

**Comment by prideout** [comment]
Yes this sample requires android 9.0.   To see how to use the old TEXTURE_ID method of `Stream` usage, you can look at the sample's history or at `sample-stream-test`.

**Comment by wudelu** [comment]
> Yes this sample requires android 9.0. To see how to use the old TEXTURE_ID method of `Stream` usage, you can look at the sample's history or at `sample-stream-test`.

Thank you. I have two questions now
1. I want to show the model in the camera preview and get the data of the preview. Can I do this? Do you have any ideas?
2. Do you have the documentation of filament API and where is it

**Comment by prideout** [comment]
You can display a model by following [this tutorial](https://medium.com/@philiprideout/getting-started-with-filament-on-android-d10b16f0ec67).  We do not have an AR sample yet (#2646).  Our materials API is documented [here](https://google.github.io/filament/Materials.html), we have javadoc comments for the Java API's and doxygen comments for the C++ API's.
