### ISSUE TITLE
Issue with glb model rendering in Android with filament and gltfio

### ISSUE THREAD

**Issue by udayk07** [google/filament#3948]
Tried to load a glb ( model attached ) model using sceneform with filament. While trying to render app got crashed. I am using latest version ( v1.9.24) of filament and gltf loader. 

Same model works fine in online gltf-viewer.
<img width="940" alt="Screenshot 2021-05-12 at 7 38 29 PM" src="https://user-images.githubusercontent.com/78372917/117993163-1b858e00-b35d-11eb-9441-2c129ad0ec0e.png">

crash log:
`java.lang.IllegalStateException: Failed to load gltf
        at com.google.ar.sceneform.rendering.RenderableInstance.createFilamentAssetModelInstance(RenderableInstance.java:133)
        at com.google.ar.sceneform.rendering.RenderableInstance.<init>(RenderableInstance.java:108)
        at com.google.ar.sceneform.rendering.Renderable.createInstance(Renderable.java:219)
        at com.google.ar.sceneform.Node.setRenderable(Node.java:864)`

filament logs:

`2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Magazine_Spring
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Magazine_Bottom_Plate
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Magazine_Catch_Plate
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Magazine_Catch_Shaft
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Trigger_Guard_Spring_Pin
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Trigger_Guard_Plunger
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Trigger_Guard
2021-05-12 19:47:32.171 3724-3724/com.example.augmentedreality E/Filament: Empty vertex buffer in Trigger_Guard_Spring`

Could anyone check it and provide solution? Thanks in advance.

[gun.zip](https://github.com/google/filament/files/6466880/gun.zip)

**Comment by romainguy** [comment]
Please provide the full logs and please try the model in our own online viewer: https://google.github.io/filament/viewer

**Comment by udayk07** [comment]
@romainguy 

Found no specific logs other than above mentioned logs. Attached full console logs for your reference.
[ar_crash_log.txt](https://github.com/google/filament/files/6467248/ar_crash_log.txt)


While loading the model in online viewer https://google.github.io/filament/viewer also model is not rendering.
<img width="1440" alt="Screenshot 2021-05-12 at 8 53 02 PM" src="https://user-images.githubusercontent.com/78372917/118002115-f1d06500-b364-11eb-8069-e9b4ecbd68e5.png">

model: https://github.com/google/filament/files/6466880/gun.zip

**Comment by romainguy** [comment]
I can reproduce with the native `gltf-viewer`. Besides all the empty vertex buffers, this gets printed as well:

```
Unable to parse /Users/romainguy/Downloads/scene.glb
```

**Comment by prideout** [comment]
This model is non-conformant; every accessor has its `count` set to 0.

This model seems to be generated by `glTF-Transform` so you might want to file a bug there.  Since this model uses draco compression, the bug in the pipeline might be when compression occurs.
