### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by chirag-qs** [google/filament#4232]
i am getting this crash very often, here is the crash log

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.filament.gltfio.Animator.clearNativeObject()' on a null object reference
       at com.google.android.filament.gltfio.FilamentAsset.clearNativeObject(FilamentAsset.java:224)
       at com.google.android.filament.gltfio.AssetLoader.destroyAsset(AssetLoader.java:168)
       at com.google.android.filament.utils.ModelViewer.destroyModel(ModelViewer.kt:221)
       at com.google.android.filament.utils.ModelViewer$addDetachListener$1.onViewDetachedFromWindow(ModelViewer.kt:273)
       at android.view.View.dispatchDetachedFromWindow(View.java:19807)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3852)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3852)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3852)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5495)
       at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5466)
       at android.view.ViewGroup.removeView(ViewGroup.java:5397)
       at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:317)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1250)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2007)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
       at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
       at android.os.Handler.handleCallback(Handler.java:888)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Device details

Device
Brand:HUAWEI
Model:P20 Pro
Orientation: Portrait
RAM free: 1.91 GB
Disk free: 6.56 GB

Operating System
Version:10
Orientation: Portrait
Rooted:No

Here is the code

  override fun onResume() {
        super.onResume()
        choreographer?.postFrameCallback(frameScheduler)
    }

    override fun onPause() {
        super.onPause()
        choreographer?.removeFrameCallback(frameScheduler)
    }

    override fun onDestroy() {
        super.onDestroy()
        choreographer?.removeFrameCallback(frameScheduler)
        modelViewer?.destroyModel()
    }

**Comment by romainguy** [comment]
destroyModel() is called by ModelViewer when the surface view is detached. You are attempting to destroy a model that's already destroyed.
