### ISSUE TITLE
Out of bounds exception when setting a texture on a RenderTarget 

### ISSUE THREAD

**Issue by overflightnz** [google/filament#4293]
**Describe the bug**
On Android setting a texture on a RenderTarget to the Color attachment point raises an exception.

I believe this was fixed via https://github.com/google/filament/commit/204fc0359c6f6d3fff198f4a1aa10f4dea29aae0 however it is still happening with 1.10.6? 

```
2021-07-12 12:03:06.174 17412-17412/io.project.colortexture E/SurfaceView: Exception configuring surface
    java.lang.ArrayIndexOutOfBoundsException: length=5; index=8
        at com.google.android.filament.RenderTarget$Builder.texture(RenderTarget.java:90)
        at io.project.colortexture.MainActivity.initRenderTargets(MainActivity.kt:103)
        at io.project.colortexture.MainActivity.access$initRenderTargets(MainActivity.kt:20)
        at io.project.colortexture.MainActivity$SurfaceCallback.onResized(MainActivity.kt:155)
        at com.google.android.filament.android.UiHelper$1.surfaceChanged(UiHelper.java:413)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:1165)
        at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:173)
        at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**To Reproduce**
Run the example project to see the exception. [ColorTexture.zip](https://github.com/google/filament/files/6797880/ColorTexture.zip)
Commenting line 103  `.texture(RenderTarget.AttachmentPoint.DEPTH, depthTexture)` fixes the issue.

**Expected behavior**
The Texture should be attached without raising an exception.

**Screenshots**
The attachment point is out of bounds due to the `ATTACHMENT_COUNT` set to 5. 
![Screen Shot 2021-07-12 at 12 09 03 PM](https://user-images.githubusercontent.com/58448744/125214224-f637e080-e309-11eb-99d2-87f1e0cc3dbb.png)

**Smartphone (please complete the following information):**
 - Device: Android simulator Pixel 3a

**Additional context**
```
dependencies {
    ...
    implementation 'com.google.android.filament:filament-android:1.10.6'
    implementation 'com.google.android.filament:gltfio-android:1.10.6'
    implementation 'com.google.android.filament:filament-utils-android:1.10.6'
    ...
}
```

Thanks.

**Comment by romainguy** [comment]
The code is already fixed but it's just not in 1.10.6. It will be in 1.10.7 tomorrow (July 12).
