### ISSUE TITLE
gltf_viewer doesn't like  being launcher many times rapidly

### ISSUE THREAD

**Issue by pixelflinger** [google/filament#4332]
An interesting stress test is to run this command on Android:
`adb shell am start -W -R 200 -n com.google.android.filament.gltf/.MainActivity`

This will launch gltf_viewer 200 times. Ideally this should work without any problem, but in practice the app crashes or hangs for various reasons. The hello_triangle test for instance works well.
Here is an example of problem it ran into:

```
2021-07-16 11:15:03.035 9894-9894/com.google.android.filament.gltf E/civetweb: cannot bind to 8082: 98 (Address already in use)
2021-07-16 11:15:03.035 9894-9894/com.google.android.filament.gltf E/Filament: Unable to start RemoteServer, see civetweb.txt for details.
2021-07-16 11:15:03.037 9894-9894/com.google.android.filament.gltf E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.gltf, PID: 9894
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.filament.gltf/com.google.android.filament.gltf.MainActivity}: java.lang.IllegalStateException: Couldn't create RemoteServer
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: Couldn't create RemoteServer
        at com.google.android.filament.utils.RemoteServer.<init>(RemoteServer.java:43)
        at com.google.android.filament.gltf.MainActivity.onCreate(MainActivity.kt:110)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by prideout** [comment]
Thanks, I'll take a look next week.  One potential issue is the TCP port on the remote UI server, it needs to be released properly (i.e.`~DebugServer()` must be called) otherwise a port conflict will occur after re-launching.

**Comment by kyadalu1** [comment]
Facing similar issue in react native
