### ISSUE TITLE
sample-hello-camera demo crash 

### ISSUE THREAD

**Issue by steven-gao** [google/filament#4670]
**Describe the bug**
i download filament code which version is 1.12.4,and build it successfuly,I run every demo successfuly except sample-hello-camera .
I would be very grateful to someone for giving me some advice

**To Reproduce**
1. run sample-hello-camera demo

**Expected behavior**
run successfuly

**Screenshots**

**Logs**
    Process: com.google.android.filament.hellocamera, PID: 27964
    java.lang.NoSuchMethodError: No static method newInstance(IIIIJ)Landroid/media/ImageReader; in class Landroid/media/ImageReader; or its super classes (declaration of 'android.media.ImageReader' appears in /system/framework/framework.jar)
        at com.google.android.filament.hellocam.CameraHelper.<init>(CameraHelper.kt:59)
        at com.google.android.filament.hellocam.MainActivity.onCreate(MainActivity.kt:97)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3093)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3256)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Desktop (please complete the following information):**
 - OS: macos
 - GPU: [e.g. NVIDIA GTX 1080]
 - Backend: [OpenGL/Vulkan]

**Smartphone (please complete the following information):**
 - Device: sumsung s10
 - OS: Android Pie 9.0

**Additional context**

**Comment by romainguy** [comment]
This particular demo runs only on API 29+, sorry about that.
