### ISSUE TITLE
Android sample-steam-test sample crash

### ISSUE THREAD

**Issue by Miao-10k** [google/filament#4839]
**Describe the bug**
I was running the sample-stream-test in android samples and modified a little code so I can start the MainActivity Twice. And I found that the app will crash when back from the second activity with the first activity's streamSource is CANVAS_STREAM_TEXID.

**To Reproduce**
1. start the MainActivity in sample-steam-test
2. touch the screen to convert the streamSource to CANVAS_STREAM_TEXID
3. start another MainActivity
4. back to the first MainActivity and It will crash

**Logs**
2021-11-11 18:18:48.451 20520-20520/com.google.android.filament.streamtest E/OpenGLRenderer: [SurfaceTexture-1-20520-4] checkAndUpdateEglState: invalid current EGLContext
2021-11-11 18:18:48.452 20520-20520/com.google.android.filament.streamtest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.streamtest, PID: 20520
    java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
        at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
        at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
        at com.google.android.filament.streamtest.StreamHelper.repaintCanvas(StreamHelper.kt:106)
        at com.google.android.filament.streamtest.MainActivity$FrameCallback.doFrame(MainActivity.kt:364)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:907)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)

**Smartphone (please complete the following information):**
 - Device: XIAOMI 8
 - OS: Android 8.1

**Comment by romainguy** [comment]
This sample is not designed to be run twice in the same process. You can however fix it by doing this in Activity's `onResume`:

`check(EGL14.eglMakeCurrent(display, surface, surface, context)) { "Error making GL context." }`
