### ISSUE TITLE
init ModelViewer(surfaceView) failure！！！

### ISSUE THREAD

**Issue by liuluyangdev** [google/filament#4867]
Can someone tell me how to use Filament in Android appropriately? Thanks!!!
My test device is HUAWEI MATE 40 PRO.
error log:
`
2021-11-18 09:43:07.108 9595-9595/com.lotus.demofilament E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lotus.demofilament, PID: 9595
    java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.filament.gltfio.UbershaderLoader.nCreateUbershaderLoader(long) (tried Java_com_google_android_filament_gltfio_UbershaderLoader_nCreateUbershaderLoader and Java_com_google_android_filament_gltfio_UbershaderLoader_nCreateUbershaderLoader__J)
        at com.google.android.filament.gltfio.UbershaderLoader.nCreateUbershaderLoader(Native Method)
        at com.google.android.filament.gltfio.UbershaderLoader.<init>(UbershaderLoader.java:44)
        at com.google.android.filament.utils.ModelViewer.<init>(ModelViewer.kt:113)
        at com.google.android.filament.utils.ModelViewer.<init>(ModelViewer.kt:132)
        at com.google.android.filament.utils.ModelViewer.<init>(ModelViewer.kt:132)
        at com.lotus.demofilament.FilamentActivity.onCreate(FilamentActivity.kt:44)
        at android.app.Activity.performCreate(Activity.java:8214)
        at android.app.Activity.performCreate(Activity.java:8202)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
`

my build.gradle:

    implementation 'com.google.android.filament:filament-android:1.14.0'
    implementation 'com.google.android.filament:gltfio-android:1.14.0'
    implementation 'com.google.android.filament:filament-utils-android:1.14.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.0'

**Comment by romainguy** [comment]
Did you call Utils.init() first? Your JNI library isn't loaded:

java.lang.UnsatisfiedLinkError: No implementation found for long com.google.android.filament.gltfio.UbershaderLoader.nCreateUbershaderLoader(long)

**Comment by liuluyangdev** [comment]
@romainguy Thanks a lot!
