### ISSUE TITLE
Unable to create animator when load a glb/gltf

### ISSUE THREAD

**Issue by teoking** [google/filament#4968]
**Describe the bug**
Load glb/gltf file failed.

**To Reproduce**
1. Download glb/gltf file [here](https://drive.google.com/drive/folders/1IRBp-WDM28E7M6JfnP0_198RtBwwZuLn?usp=sharing)
2. Load 'mytest.glb' in sample-gltf-viewer.

**Expected behavior**
glb/gltf load successfully

**Logs**
```
2021-12-14 18:03:05.515 8215-8215/com.google.android.filament.gltf E/Filament: Failed cgltf validation.
2021-12-14 18:03:05.515 8215-8215/com.google.android.filament.gltf E/Filament: Cannot create animator before resource loading.
2021-12-14 18:03:05.539 8215-8263/com.google.android.filament.gltf E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.google.android.filament.gltf, PID: 8215
    java.lang.IllegalStateException: Unable to create animator
        at com.google.android.filament.gltfio.FilamentAsset.getAnimator(FilamentAsset.java:212)
        at com.google.android.filament.utils.ModelViewer$fetchResources$2.invokeSuspend(ModelViewer.kt:347)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7395)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Desktop (please complete the following information):**
 - OS: Android
 - GPU: Qualcomm
 - Backend: [OpenGL]

**Additional context**
The glb and gltf were tested on the following viewers and rendered both fine:
* https://gltf-viewer.donmccurdy.com/
* https://sandbox.babylonjs.com/
* Blender Desktop

**Comment by teoking** [comment]
Test the glb on Mac M1 with gltf_viewer, see the following error:
```
/Users/ted/Documents/GitHub/filament/cmake-build-debug/samples/gltf_viewer /Users/ted/Documents/Work/design/mytest.glb
FEngine (64 bits) created at 0x135800000 (threading is enabled)
FEngine resolved backend: Metal
Selected physical device 'Apple M1'
Supported GPU families: 
  MTLGPUFamilyCommon3
  MTLGPUFamilyApple7
  MTLGPUFamilyMac2
Features:
  readWriteTextureSupport: true

in void utils::panic(const char *, const char *, int, const char *):32
in file /Users/ted/Documents/GitHub/filament/libs/utils/src/debug.cpp
reason: /Users/ted/Documents/GitHub/filament/filament/backend/src/metal/MetalDriver.mm:1333: failed assertion `vb->buffers[attribute.buffer]'

#0	gltf_viewer                            0x103a19990 utils::CallStack::update(unsigned long) + 32
#1	gltf_viewer                            0x103a19964 utils::CallStack::unwind(unsigned long) + 44
#2	gltf_viewer                            0x103a37488 utils::details::panicLog(char const*, char const*, int, char const*, ...) + 212
#3	gltf_viewer                            0x103a18bbc utils::panic(char const*, char const*, int, char const*) + 92
#4	gltf_viewer                            0x102d15f44 filament::backend::metal::MetalDriver::draw(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>) + 2900
#5	gltf_viewer                            0x102d4a688 decltype(auto) filament::backend::invoke<filament::backend::metal::MetalDriver, void (filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive> >(void (filament::backend::metal::MetalDriver::*)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, filament::backend::PipelineState&&, filament::backend::Handle<filament::backend::HwRenderPrimitive>&&) + 192
#6	gltf_viewer                            0x102d4a5a8 decltype(auto) filament::backend::trampoline<void (filament::backend::metal::MetalDriver::*)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, std::__1::tuple<filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive> >, 0ul, 1ul>(void (filament::backend::metal::MetalDriver::*&&)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, std::__1::tuple<filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive> >&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>) + 128
#7	gltf_viewer                            0x102d4a4f4 decltype(auto) filament::backend::apply<void (filament::backend::metal::MetalDriver::*)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, std::__1::tuple<filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive> > >(void (filament::backend::metal::MetalDriver::*&&)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, std::__1::tuple<filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive> >&&) + 72
#8	gltf_viewer                            0x102d153e0 void filament::backend::CommandType<void (filament::backend::Driver::*)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>)>::Command<&(filament::backend::Driver::draw(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>))>::execute<void (filament::backend::metal::MetalDriver::*)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&>(void (filament::backend::metal::MetalDriver::*&&)(filament::backend::PipelineState, filament::backend::Handle<filament::backend::HwRenderPrimitive>), filament::backend::metal::MetalDriver&, filament::backend::CommandBase*, long*) + 104
#9	gltf_viewer                            0x102d0f738 filament::backend::ConcreteDispatcher<filament::backend::metal::MetalDriver>::draw(filament::backend::Driver&, filament::backend::CommandBase*, long*) + 68
#10	gltf_viewer                            0x102c98a50 filament::backend::CommandBase::execute(filament::backend::Driver&) + 44
#11	gltf_viewer                            0x102c98a10 filament::backend::CommandStream::execute(void*)::$_0::operator()() const + 60
#12	gltf_viewer                            0x102c989b4 decltype(std::__1::forward<filament::backend::CommandStream::execute(void*)::$_0&>(fp)()) std::__1::__invoke<filament::backend::CommandStream::execute(void*)::$_0&>(filament::backend::CommandStream::execute(void*)::$_0&) + 28
#13	gltf_viewer                            0x102c98968 void std::__1::__invoke_void_return_wrapper<void, true>::__call<filament::backend::CommandStream::execute(void*)::$_0&>(filament::backend::CommandStream::execute(void*)::$_0&) + 28
#14	gltf_viewer                            0x102c98940 std::__1::__function::__alloc_func<filament::backend::CommandStream::execute(void*)::$_0, std::__1::allocator<filament::backend::CommandStream::execute(void*)::$_0>, void ()>::operator()() + 28
#15	gltf_viewer                            0x102c9725c std::__1::__function::__func<filament::backend::CommandStream::execute(void*)::$_0, std::__1::allocator<filament::backend::CommandStream::execute(void*)::$_0>, void ()>::operator()() + 28
#16	gltf_viewer                            0x102b6e55c std::__1::__function::__value_func<void ()>::operator()() const + 56
#17	gltf_viewer                            0x102b6e518 std::__1::function<void ()>::operator()() const + 24



Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by romainguy** [comment]
The interesting bits are here:

```
2021-12-14 18:03:05.515 8215-8215/com.google.android.filament.gltf E/Filament: Failed cgltf validation.
2021-12-14 18:03:05.515 8215-8215/com.google.android.filament.gltf E/Filament: Cannot create animator before resource loading.
```

Looks like the asset might not be valid or cgltf has a parsing bug.

**Comment by teoking** [comment]
It seems the asset parsing failed on Android device, the parsing is passed on Mac M1, but failed on drawing.
Not tested on Linux yet, I'll do that later.

**Comment by pixelflinger** [comment]
Invalid asset. Reopen if this happens again with a valid asset.
