### ISSUE TITLE
Android SDK 22 runtime crash

### ISSUE THREAD

**Issue by rawnsley** [google/filament#594]
**Describe the bug**
The sample Android app hello-triangle crashes at runtime on Android SDK 22 (Lollipop MR1) device.

**To Reproduce**
1. Build the hello-triangle app against source or against the sceneform-1.7pr1 release AAR files.
2. Deploy and run on Android SDK 22 device.

**Expected behavior**
App should run without crashing as it does on alternative test device, a Pixel phone on SDK 28 in this case.

**LogCat**

```
12-07 15:14:51.150 25699-25699/com.google.android.filament.hellotriangle W/linker: libfilament-jni.so: unused DT entry: type 0x6ffffffe arg 0x8b30
12-07 15:14:51.150 25699-25699/com.google.android.filament.hellotriangle W/linker: libfilament-jni.so: unused DT entry: type 0x6fffffff arg 0x3
12-07 15:14:51.152 25699-25699/com.google.android.filament.hellotriangle E/art: dlopen("/data/app/com.google.android.filament.hellotriangle-1/lib/arm/libfilament-jni.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libfilament-jni.so"...
12-07 15:14:51.155 25699-25699/com.google.android.filament.hellotriangle D/AndroidRuntime: Shutting down VM
12-07 15:14:51.160 25699-25699/com.google.android.filament.hellotriangle E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.hellotriangle, PID: 25699
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libfilament-jni.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:371)
        at java.lang.System.loadLibrary(System.java:988)
        at com.google.android.filament.Filament.<clinit>(Filament.java:22)
        at com.google.android.filament.Filament.init(Filament.java:30)
        at com.google.android.filament.hellotriangle.MainActivity.<clinit>(MainActivity.kt:46)
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.Class.newInstance(Class.java:1606)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2242)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

```

**Smartphone (please complete the following information):**
 - Device: RockChip 3288 device
 - OS: Android Lollipop MR1

**Additional context**
A cursory search of the error message suggests that one of the NDK libraries pulls in a reference to __register_atfork, which was only added in SDK 23. I'm not sure if this is an NDK bug, a compiler options bug, or if Filament genuinely only supports SDK23+.

**Comment by romainguy** [comment]
Thanks! We compile with API level 24 to access optional features but it apparently has side effects. We need to figure out a way to compile for API level 21.

**Comment by romainguy** [comment]
Apparently everything compiles just fine with API level 24, I need to investigate why we switch to this level. Might be for optimizations.

**Comment by romainguy** [comment]
Seems to be working fine with API level 21.

**Comment by rawnsley** [comment]
That worked. Thank you for the super quick response and fix!

**Comment by romainguy** [comment]
You're welcome! Thanks for the port, and sorry you had to deal with this!
