### ISSUE TITLE
build AAR  faild。Unsupported class file major version 63

### ISSUE THREAD

**Issue by jaccen** [google/filament#6327]
**Describe the bug**
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 63
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
        ... 25 more

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 1 executed, 1 up-to-date
Watched directory hierarchies: [/Users/jaccen/Desktop/Engine/filament/android]
Stopped 1 worker daemon(s).
**To Reproduce**
1. mac os  build   out/android-release/filament/lib/arm64-v8a.
2、$ ./gradlew -Pcom.google.android.filament.dist-dir=../../out/android-release/filament assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '/Users/jaccen/Desktop/Engine/filament/android/buildSrc/src/main/groovy/FilamentPlugin.groovy' Unsupported class file major version 63

**Comment by romainguy** [comment]
Looks like you are building different bits with different JDKs. Class file version 63 is from Java 19.
