### ISSUE TITLE
ANR Happens during onViewDetachedFromWindow

### ISSUE THREAD

**Issue by chiragchauhan1073** [google/filament#6627]
**Describe the bug**
ANR happens inside ModelViewer class when filament tried to Destroy Renderer. 

**Logs**
main (native):tid=1 systid=29424 
#00 pc 0x85c6c libc.so (syscall + 28)
#01 pc 0x1722d8 split_config.arm64_v8a.apk + 4096
       at com.google.android.filament.Engine.nDestroyRenderer(Native method)
       at com.google.android.filament.Engine.destroyRenderer(Engine.java:494)
       at com.google.android.filament.utils.ModelViewer$addDetachListener$1.onViewDetachedFromWindow(ModelViewer.kt:324)
       at android.view.View.dispatchDetachedFromWindow(View.java:20945)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3948)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3948)
       at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3948)
       at android.view.ViewGroup.endViewTransition(ViewGroup.java:7197)
       at androidx.fragment.app.FragmentContainerView.endViewTransition(FragmentContainerView.java:291)
       at androidx.fragment.app.DefaultSpecialEffectsController$4$1.run(DefaultSpecialEffectsController.java:258)
       at android.os.Handler.handleCallback(Handler.java:978)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:357)
       at android.app.ActivityThread.main(ActivityThread.java:8090)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

**Smartphone (please complete the following information):**
 - OS: Android
 - Model: Moto G Power (2022)
 - Version: Android 12

**This started to happen after updating the filament to version 1.31.3. additionally, colour grading is added. below are the code snippets**

 val colorGrading = ColorGrading.Builder()
            .toneMapping(ColorGrading.ToneMapping.FILMIC)
            .build(engine)

**Comment by pixelflinger** [comment]
Do you have more infos? (which device, does it happen on the emulator, does it happen often). And can you provide a sample to reproduce?

**Comment by Reign9201** [comment]
<img width="1652" height="698" alt="Image" src="https://github.com/user-attachments/assets/a03a9deb-751c-44cb-8000-54a3e79052d4" />
I also encountered the same issue, mainly on the MT67 series chips, a lot of them.
