### ISSUE TITLE
Android SDK 28 runtime crash

### ISSUE THREAD

**Issue by xzhan96** [google/filament#689]
**Describe the bug**
All the sample Android app  crashes at runtime on Android SDK 28  (Android 9) device.
I see the issue #594, but it seems my case is not the same with that. I think my issue should be related the compiling, but it shows the "BUILD SUCCESSFUL" message.

**To Reproduce**
1. Build the filament by using the command: 
    ./build.sh -p desktop -i release
    ./build.sh -p android release
This step is successfully.
2. Import the sample into android studio 3.2.1 and deploy app on Android SDK 28 device.

**Expected behavior**

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 20, I think the issue not related with phone.
 - OS: Android  9.0

**Additional context**
The crash log as below:
2019-01-09 17:32:21.739 30516-30516/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.hellotriangle, PID: 30516
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/base.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_dependencies_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_resources_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_0_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_1_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_2_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_3_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_4_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_5_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_6_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_7_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_8_apk.apk", zip file "/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libfilament-jni.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.google.android.filament.Filament.<clinit>(Filament.java:22)
        at com.google.android.filament.Filament.init(Unknown Source:0)
        at com.google.android.filament.hellotriangle.MainActivity.<clinit>(MainActivity.kt:44)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3210)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by xzhan96** [comment]
[/data/app/com.google.android.filament.hellotriangle-Ht9bhZ4IdEJdVH07vZLAsw==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libfilament-jni.so"

This is the root cause, but I don't know why this happen even the build successful.

**Comment by romainguy** [comment]
You may not be building the APK for the correct ABI. Open the build variants tool window in Android Studio and make sure you are bulding "universal" or "arm64".

**Comment by xzhan96** [comment]
@romainguy That works. Thanks a lot for your quick response and fix!
