### ISSUE TITLE
Android sample code crashes while loading high resolution IBL

### ISSUE THREAD

**Issue by Sweenall** [google/filament#701]
I generated an IBL using the following command on Mac OSX:
./cmgen -x . --extract-blur=0.0 --format=rgbm --size=256 pillars_2k.hdr

It worked perfectly when I loaded it on android sample code: image-based-lighting.

But when I generated the IBL of size 512 (./cmgen -x . --extract-blur=0.0 --format=rgbm --size=512 pillars_2k.hdr) then loaded it in the sample code, the app crashes at
“loadIndirectLight(assets: AssetManager, name: String, engine: Engine): Pair<IndirectLight, Texture>” function.

Am I missing something? How do I render high resolution IBL?

**Comment by romainguy** [comment]
It's an easy fix. In `loadIndirectLight`, replace the first line with:

```kotlin
val (w, h) = peekSize(assets, "$name/m0_nx.rgbm")
```

**Comment by romainguy** [comment]
Thanks for the report, I've updated the samples!

**Comment by Sweenall** [comment]
Hi romainguy,
I added the fix you suggested but it's still crashing. When I go deeper into the code it crashes at "public IndirectLight build(@NonNull Engine engine) {}" function in "IndirectLight.java" class, it is throwing an exception "Couldn't create IndirectLight"

Here is the crash log:

2019-01-16 11:44:53.163 7048-7048/com.google.android.filament.textured E/Filament: in filament::IndirectLight *filament::IndirectLight::Builder::build(filament::Engine &):100
    reason: reflection map must be 256x256 and have 9 mipmap levels
2019-01-16 11:48:28.074 7048-7048/com.google.android.filament.textured D/AndroidRuntime: Shutting down VM
2019-01-16 11:48:28.096 7048-7048/com.google.android.filament.textured E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.filament.textured, PID: 7048
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.filament.textured/com.google.android.filament.textured.MainActivity}: java.lang.IllegalStateException: Couldn't create IndirectLight
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.IllegalStateException: Couldn't create IndirectLight
        at com.google.android.filament.IndirectLight$Builder.build(IndirectLight.java:88)
        at com.google.android.filament.textured.IblLoaderKt.loadIndirectLight(IblLoader.kt:92)
        at com.google.android.filament.textured.IblLoaderKt.loadIbl(IblLoader.kt:44)
        at com.google.android.filament.textured.MainActivity.loadImageBasedLight(MainActivity.kt:548)
        at com.google.android.filament.textured.MainActivity.setupScene(MainActivity.kt:439)
        at com.google.android.filament.textured.MainActivity.onCreate(MainActivity.kt:309)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by romainguy** [comment]
The reason is in the exception message. The cubemap for the skybox itself can be high resolution with the fix but the cubemap for specular reflections must be 256x256 per face. This is because the shaders need to know how many mip levels there are. Note that 256 is already fairly high res for this kind of cubemap and on par with what engines like Unreal or Frostbite do.

**Comment by Sweenall** [comment]
Thanks for the quick response. :)
 In this "fun loadIndirectLight( assets: AssetManager, name: String, engine: Engine): Pair<IndirectLight, Texture>" while building the texture if I keep the  levels = 9, it works perfectly fine. For example for IBL of size 1024, I updated the texture:
val texture = Texture.Builder()
            .width(w)
            .height(h)
            .levels(9)
            .format(Texture.InternalFormat.RGBA8)
            .rgbm(true)
            .sampler(Texture.Sampler.SAMPLER_CUBEMAP)
            .build(engine)

**Comment by romainguy** [comment]
You can do this but it will lead to incorrect results on screen (and potentially GL errors or crashes later).

**Comment by Sweenall** [comment]
Understood. Thanks.
