### ISSUE TITLE
NullPointerException android.filament.Texture.getNativeObject() after updating to Filament v1.41.0

### ISSUE THREAD

**Issue by sebapian** [google/filament#7121]
**Description of the bug:**

I am getting a NullPointerException after upgrading to from Filament v1.29.0 to v1.41.0. Was working just fine before upgrading. As soon as the app tries to load model, app crashes with error logs below. 

**Code snippet:**
![image](https://github.com/google/filament/assets/89761448/af63a60b-b83a-481c-90cc-4cde985b3f7c)

**Logs:**
```
FATAL EXCEPTION: main
Process: nz.co.genesisenergy.gema.debug, PID: 5249
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.google.android.filament.Texture.getNativeObject()' on a null object reference
    at com.google.android.filament.View.setFogOptions(View.java:968)
    at nz.co.genesisenergy.genesis.liverender.internal.FilamentRendererHandler.updateFog(FilamentRendererHandler.kt:280)
    at nz.co.genesisenergy.genesis.liverender.internal.FilamentRendererHandler.setup$lambda$0(FilamentRendererHandler.kt:132)
    at nz.co.genesisenergy.genesis.liverender.internal.FilamentRendererHandler.$r8$lambda$x_GHSsJ2d9Irxt-rELOqp1JGv9M(Unknown Source:0)
    at nz.co.genesisenergy.genesis.liverender.internal.FilamentRendererHandler$$ExternalSyntheticLambda3.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Desktop:**
 - MacOS
 - M1 Max

**Smartphone:**
 - Pixel 5 Emulator
 - API 33

**Comment by romainguy** [comment]
Thanks for reporting this, I'll fix it right away.
