### ISSUE TITLE
SegFault samples with Vulkan after recent PR on HandleAllocator

### ISSUE THREAD

**Issue by jaesung-cs** [google/filament#7563]
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
In PR merged 2 days ago: https://github.com/google/filament/pull/7557/files#diff-8b46d1205c6c34c74ed46aeab7c5acf3a37330fed9848b474943ff31122f28b7R45-R47
It seems logically that the offsets are wrong. Correct ones would be
```c++
    mPool0 = PoolAllocator< P0, 16>(p0, count * P0);
    mPool1 = PoolAllocator< P1, 16>(p1, count * P1);
    mPool2 = PoolAllocator< P2, 16>(p2, count * P2);
```

**To Reproduce**
Any sample with vulkan backend
```bash
$ ./out/cmake-debug/samples/hellotriangle -a vulkan
```

**Expected behavior**
`hellotriangle` worked after the fix above, tested locally.

**Logs**
```bash
$ ./out/cmake-debug/samples/hellotriangle -a vulkan
WARNING: Using soft CircularBuffer (12288 KiB)
FEngine (64 bits) created at 0x561aa1abdf00 (threading is enabled)
Vulkan device driver: NVIDIA 535.154.05
Selected physical device 'NVIDIA GeForce RTX 4090' from 2 physical devices. (vendor 0x10de, device 0x2684, driver 0x85e68140, api 1.3)
Segmentation fault (core dumped)
```
gdb log:
```
Thread 20 "FEngine::loop" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2ffd640 (LWP 140199)]
0x0000555555b7b89c in utils::FreeList::init (begin=0x7fffc64a6a00, end=0x7fffc69185c0, elementSize=320, alignment=16, extra=0) at /workspace/filament/libs/utils/src/Allocator.cpp:102
102             cur->next = next;
(gdb) bt 4
#0  0x0000555555b7b89c in utils::FreeList::init (begin=0x7fffc64a6a00, end=0x7fffc69185c0, elementSize=320, alignment=16, extra=0) at /workspace/filament/libs/utils/src/Allocator.cpp:102
#1  0x0000555555b7ba81 in utils::FreeList::FreeList (this=0x7fffe2ffc0d8, begin=0x7fffc64a6a00, end=0x7fffc69185c0, elementSize=320, alignment=16, extra=0)
    at /workspace/filament/libs/utils/src/Allocator.cpp:113
#2  0x00005555558da139 in utils::PoolAllocator<320ul, 16ul, 0ul, utils::FreeList>::PoolAllocator (this=0x7fffe2ffc0d8, begin=0x7fffc64a6a00, size=4660160)
    at /workspace/filament/libs/utils/include/utils/Allocator.h:397
#3  0x00005555558d9ff0 in filament::backend::HandleAllocator<80ul, 176ul, 320ul>::Allocator::Allocator (this=0x7fffd4454fe8, area=...) at /workspace/filament/filament/backend/src/HandleAllocator.cpp:47
(More stack frames follow...)
(gdb) 
```
Seg fault at `#3 HandleAllocator.cpp:47`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - GPU: NVIDIA GeForce RTX 4090
 - Backend: Vulkan

**Additional context**
`hellotriangle` with OpenGL worked though.

**Comment by pixelflinger** [comment]
thanks, good catch.
